---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: install
  image: node:13
  commands:
  - npm install

- name: build
  image: node:13
  environment:
    NODE_ENV: production
  commands:
  - npm run build

- name: publish
  image: appleboy/gh-pages
  pull: always
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    pages_directory: dist
